all:
  hosts:
    dev-master01:
      ansible_host: 172.16.100.121
      ip: 172.16.100.121
      access_ip: 172.16.100.121
      ansible_user: jaist-lab
    dev-master02:
      ansible_host: 172.16.100.122
      ip: 172.16.100.122
      access_ip: 172.16.100.122
      ansible_user: jaist-lab
    dev-master03:
      ansible_host: 172.16.100.123
      ip: 172.16.100.123
      access_ip: 172.16.100.123
      ansible_user: jaist-lab
    dev-node01:
      ansible_host: 172.16.100.131
      ip: 172.16.100.131
      access_ip: 172.16.100.131
      ansible_user: jaist-lab
    dev-node02:
      ansible_host: 172.16.100.132
      ip: 172.16.100.132
      access_ip: 172.16.100.132
      ansible_user: jaist-lab
    dev-node03:
      ansible_host: 172.16.100.133
      ip: 172.16.100.133
      access_ip: 172.16.100.133
      ansible_user: jaist-lab
  children:
    kube_control_plane:
      hosts:
        dev-master01:
        dev-master02:
        dev-master03:
    kube_node:
      hosts:
        dev-node01:
        dev-node02:
        dev-node03:
    etcd:
      hosts:
        dev-master01:
        dev-master02:
        dev-master03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
