all:
  hosts:
    dev-master01:
      ansible_host: 172.16.200.121
      ip: 172.16.200.121
      access_ip: 172.16.100.121
      ansible_user: jaist-lab
    dev-master02:
      ansible_host: 172.16.200.122
      ip: 172.16.200.122
      access_ip: 172.16.100.122
      ansible_user: jaist-lab
    dev-master03:
      ansible_host: 172.16.200.123
      ip: 172.16.200.123
      access_ip: 172.16.100.123
      ansible_user: jaist-lab
    dev-node01:
      ansible_host: 172.16.200.124
      ip: 172.16.200.124
      access_ip: 172.16.100.124
      ansible_user: jaist-lab
    dev-node02:
      ansible_host: 172.16.200.125
      ip: 172.16.200.125
      access_ip: 172.16.100.125
      ansible_user: jaist-lab
  children:
    kube_control_plane:
      hosts:
        dev-master01:
        dev-master02:
        dev-master03:
    kube_node:
      hosts:
        dev-node01:
        dev-node02:
    etcd:
      hosts:
        dev-master01:
        dev-master02:
        dev-master03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}