all:
  hosts:
    sandbox-master01:
      ansible_host: 172.16.200.131
      ip: 172.16.200.131
      access_ip: 172.16.200.131
      ansible_user: jaist-lab
    sandbox-master02:
      ansible_host: 172.16.200.132
      ip: 172.16.200.132
      access_ip: 172.16.200.132
      ansible_user: jaist-lab
    sandbox-master03:
      ansible_host: 172.16.200.133
      ip: 172.16.200.133
      access_ip: 172.16.200.133
      ansible_user: jaist-lab
    sandbox-node01:
      ansible_host: 172.16.200.134
      ip: 172.16.200.134
      access_ip: 172.16.200.134
      ansible_user: jaist-lab
    sandbox-node02:
      ansible_host: 172.16.200.135
      ip: 172.16.200.135
      access_ip: 172.16.200.135
      ansible_user: jaist-lab
  children:
    kube_control_plane:
      hosts:
        sandbox-master01:
        sandbox-master02:
        sandbox-master03:
    kube_node:
      hosts:
        sandbox-node01:
        sandbox-node02:
    etcd:
      hosts:
        sandbox-master01:
        sandbox-master02:
        sandbox-master03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}