all:
  hosts:
    master01:
      ansible_host: 172.16.200.101
      ip: 172.16.200.101
      access_ip: 172.16.200.101
      ansible_user: jaist-lab
    master02:
      ansible_host: 172.16.200.102
      ip: 172.16.200.102
      access_ip: 172.16.200.102
      ansible_user: jaist-lab
    master03:
      ansible_host: 172.16.200.103
      ip: 172.16.200.103
      access_ip: 172.16.200.103
      ansible_user: jaist-lab
    node01:
      ansible_host: 172.16.200.104
      ip: 172.16.200.104
      access_ip: 172.16.200.104
      ansible_user: jaist-lab
    node02:
      ansible_host: 172.16.200.105
      ip: 172.16.200.105
      access_ip: 172.16.200.105
      ansible_user: jaist-lab
    dlcsv1:
      ansible_host: 172.16.100.31
      ip: 172.16.100.31
      access_ip: 172.16.200.31
      ansible_user: jaist-lab
    dlcsv2:
      ansible_host: 172.16.100.32
      ip: 172.16.100.32
      access_ip: 172.16.200.32
      ansible_user: jaist-lab

  children:
    kube_control_plane:
      hosts:
        master01:
        master02:
        master03:
    kube_node:
      hosts:
        node01:
        node02:
        dlcsv1:
        dlcsv2:
    etcd:
      hosts:
        master01:
        master02:
        master03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}