all:
  hosts:
    master01:
      ansible_host: 172.16.100.101
      ip: 172.16.100.101
      access_ip: 172.16.100.101
      ansible_user: jaist-lab
    master02:
      ansible_host: 172.16.100.102
      ip: 172.16.100.102
      access_ip: 172.16.100.102
      ansible_user: jaist-lab
    master03:
      ansible_host: 172.16.100.103
      ip: 172.16.100.103
      access_ip: 172.16.100.103
      ansible_user: jaist-lab
    node01:
      ansible_host: 172.16.100.111
      ip: 172.16.100.111
      access_ip: 172.16.100.111
      ansible_user: jaist-lab
    node02:
      ansible_host: 172.16.100.112
      ip: 172.16.100.112
      access_ip: 172.16.100.112
      ansible_user: jaist-lab
    node03:
      ansible_host: 172.16.100.113
      ip: 172.16.100.113
      access_ip: 172.16.100.113
      ansible_user: jaist-lab
  children:
    kube_control_plane:
      hosts:
        master01:
        master02:
        master03:
    kube_node:
      hosts:
        node01:
        node02:
        node03:
    etcd:
      hosts:
        master01:
        master02:
        master03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
