apiVersion: v1
kind: ConfigMap
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubelet-csr-approver
    app.kubernetes.io/instance: kubelet-csr-approver
data:
  config.yaml: |
    # DNS解決を完全にバイパス（最重要）
    bypassDNSResolution: true
    
    # ホスト名チェックを完全にバイパス
    bypassHostnameCheck: true
    
    # すべての検証をスキップ
    bypassIpValidation: true
    
    # system:nodeプレフィックスを持つすべてのリクエストを許可
    providerRegex: "^system:node:.*"
    
    # 証明書の有効期限（5年 = 5 * 365 * 24 * 60 * 60 秒 ）
    maxExpirationSeconds: 157680000  

    # 許可するDNS名（ワイルドカード使用）
    allowedDNSNames:
      - "*"
    
    # 許可するIP範囲（すべて許可）
    allowedIPs:
      - "0.0.0.0/0"
