apiVersion: v1
kind: ConfigMap
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
data:
  config.yaml: |
    # DNS解決の問題を回避
    bypassDNSResolution: true
    
    # ホスト名チェックをバイパス
    bypassHostnameCheck: true
    
    # system:nodeプレフィックスを持つリクエストを許可
    providerRegex: "^system:node:.*"
    
    # 証明書の有効期限（1年 = 31536000秒）
    maxExpirationSeconds: 31536000
    
    # 許可するDNS名のリスト
    allowedDNSNames:
      - "*.cluster.local"
      - "*.kube-system.svc.cluster.local"
      - "dev-master01"
      - "dev-master02"
      - "dev-master03"
      - "dev-node01"
      - "dev-node02"
      - "dev-node03"
      - "172.16.100.121"
      - "172.16.100.122"
      - "172.16.100.123"
      - "172.16.100.131"
      - "172.16.100.132"
      - "172.16.100.133"
