---
# Kubernetes cluster name
cluster_name: production-cluster

# Kubernetes version (vプレフィックス不要)
kube_version: 1.31.3

# Container runtime
container_manager: containerd

# CRI-O設定（containerdを使用するため無効化）
download_container: true
skip_downloads: false

# Kube-proxy mode
kube_proxy_mode: ipvs
kube_proxy_strict_arp: true

# CNI plugin
kube_network_plugin: calico

# Service subnet (Productionネットワーク)
kube_service_addresses: 10.233.0.0/18

# Pod subnet (Productionネットワーク)
kube_pods_subnet: 10.233.64.0/18

# Network plugin settings
enable_dual_stack_networks: false

# DNS設定
dns_mode: coredns
dns_cores_per_replica: 256
dns_min_replicas: 2
enable_nodelocaldns: true
enable_nodelocaldns_secondary: false

# Kubelet設定
kubelet_max_pods: 110
kube_read_only_port: 0
kubelet_rotate_server_certificates: true

# APIサーバー設定
kube_apiserver_bind_address: 0.0.0.0
kube_apiserver_insecure_port: 0

# 証明書設定
auto_renew_certificates: true
auto_renew_certificates_systemd_calendar: "Mon *-*-1,2,3,4,5,6,7 03:{{ groups['kube_control_plane'].index(inventory_hostname) }}0:00"

# Audit log (Production環境のみ有効)
kubernetes_audit: true
audit_log_path: /var/log/kubernetes/audit.log
audit_log_maxage: 30
audit_log_maxbackups: 10
audit_log_maxsize: 100

# Feature Gates
kube_feature_gates:
  - "RotateKubeletServerCertificate=true"

# Encryption at rest (本番環境推奨)
kube_encrypt_secret_data: true

# Pod Security
podsecuritypolicy_enabled: false
pod_security_policy_enabled: false

# Metrics Server
metrics_server_enabled: true

# Helm
helm_enabled: true

# kubectl設定（非推奨パラメータ削除）
# kubectl_localhost: true  # 削除
# kubeconfig_localhost: true  # 削除

# kubeconfig配置
kube_config_dir: /etc/kubernetes
credentials_dir: "{{ inventory_dir }}/credentials"

# Admission Controllers
kube_apiserver_enable_admission_plugins:
  - NodeRestriction
  - NamespaceLifecycle
  - LimitRanger
  - ServiceAccount
  - DefaultStorageClass
  - MutatingAdmissionWebhook
  - ValidatingAdmissionWebhook
  - ResourceQuota
  - Priority

# Authorization modes
kube_authorization_modes:
  - Node
  - RBAC
## タイムアウト設定（マルチマスター構成での安定性向上）
kubeadm_init_timeout: 600s
kubeadm_join_timeout: 600s

## nginx-proxy無効化（マルチマスター構成でも直接接続）
loadbalancer_apiserver_localhost: false

## マルチマスター構成のための証明書アップロード設定（重要）
kubeadm_init_phases:
  - "preflight"
  - "certs"
  - "kubeconfig"
  - "etcd"
  - "control-plane"
  - "upload-config"
  - "upload-certs"
  - "bootstrap-token"
  - "addon"

# 証明書の自動アップロード有効化
kubeadm_upload_certs: true

# Control Plane join時のリトライ設定
kubeadm_control_plane_join_retries: 5
kubeadm_control_plane_join_delay: 30

## 証明書アップロードの強制設定
kubeadm_certificate_key_auto_renew: false
kubeadm_init_upload_certs: true

## Control Plane join前に証明書を確実にアップロード
kubeadm_control_plane_join_wait_for_certs: true