---
# 基本設定のみ
cluster_name: production-cluster
kube_version: 1.31.3

# Container runtime
container_manager: containerd

# Kube-proxy
kube_proxy_mode: ipvs

# CNI plugin
kube_network_plugin: calico

# Network設定
kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18

# DNS設定
dns_mode: coredns
enable_nodelocaldns: true

# Kubelet設定
kubelet_max_pods: 110
kubelet_rotate_server_certificates: true

# マルチマスター構成（シンプル設定）
loadbalancer_apiserver_localhost: true

# 証明書自動更新
auto_renew_certificates: true

# Metrics Server
metrics_server_enabled: true

# Helm
helm_enabled: true

# Authorization
kube_authorization_modes:
  - Node
  - RBAC
