apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- storage.yaml
- deployment.yaml
- ingress.yaml
- configmap-gpu.yaml

labels:
- pairs:
    environment: production
